version: "3.7"
services:
  mariadb:
    container_name: mariadb
    image: mariadb:10.6
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --skip-innodb-read-only-compressed # Temporary fix for MariaDB 10.6
    environment:
      MYSQL_ROOT_PASSWORD: <db_root_password>
    volumes:
      - mariadb-data:/var/lib/mysql
    ports:
      - "3307:3306"
      
  redis-cache:
    container_name: redis-cache
    image: redis:alpine

  redis-queue:
    container_name: redis-queue
    image: redis:alpine

  redis-socketio:
    container_name: redis-socketio
    image: redis:alpine

  frappe:
    container_name: frappe
    image: frappe/bench:latest
    command: sleep infinity
    environment:
      - SHELL=/bin/bash
    volumes:
      - ..:/workspace:cached
    working_dir: /workspace/development
    ports:
      - "<IP>:8001-8006:8001-8006"
      - "<IP>:9001-9006:9001-9006"

volumes:
  mariadb-data:
  postgresql-data:
